/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arrayList;

public class App {

  public static void main(String[] args) {
    linkedList List = new linkedList();
    // insert method
    List.insert(10);
    List.insert(20);
    List.insert(30);

    //include method
    List.include(2);
    List.include(4);
    List.include(6);

    //toSrting method

    List.toString();



  }
}
