/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arrayList;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  @Test public void testlinkList() {
    //Can successfully instantiate an empty linked list
    linkedList list1 = new linkedList();
    assertNull("empty list", list.head);


    //Can properly insert into the linked list
    linkedList list2 = new linkedList();

    list2.insert(10);
    assertEquals("insert to the likedlist" , list2.insert.data);


    //The head property will properly point to the first node in the linked list
    linkedList list3 = new linkedList();

    list3.insert(10);
    list3.insert(100);

    assertEquals("test insert to the linkedlist",10,list3.head.data);


    //Can properly insert multiple nodes into the linked list
    LinkedList list4 = new LinkedList();
    list4.insert(10);
    list4.insert(100);

    assertEquals("test multiple insert method by checking if tail is not null and equal to last node",10,
      list4.tail.data);


    //Will return true when finding a value within the linked list that exists
    LinkedList list5 = new LinkedList();
    list5.insert(10);
    list5.insert(100);
    list5.insert(1000);

    assertEquals("test includes method when finding a value the output is true",true,
      list5.includes(100));


    //Will return false when searching for a value in the linked list that does not exist
    assertEquals("test includes method when not finding a value the output is false",false,
      list5.includes(10));

    //Can properly return a collection of all the values that exist in the linked list
    String out = "{ 10 } -> { 20 } -> { 30 } -> NULL";
    assertEquals("test toStr method that return all list values",out,
      list5.toStr());



  }
}
