/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertion;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void testAppHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  }

  @Test
  public void insertionTest() {
    int[] arr = {};
    assertEquals("[]", Arrays.toString(App.insertionSort(arr)));
  }

  @Test
  public void insertionTest1() {
    int[] arr = {8, 4, 23, 42, 16, 15};
    assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(App.insertionSort(arr)));
  }


  @Test
  public void insertionTest2() {
    int[] arr = {20, 18, 12, 8, 5, -2};
    assertEquals("[-2, 5, 8, 12, 18, 20]", Arrays.toString(App.insertionSort(arr)));
  }

  @Test
  public void insertionTest3() {
    int[] arr = {5, 12, 7, 5, 5, 7};
    assertEquals("[5, 5, 5, 7, 7, 12]", Arrays.toString(App.insertionSort(arr)));
  }

  @Test
  public void insertionTest4() {
    int[] arr = {2, 3, 5, 7, 13, 11};
    assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(App.insertionSort(arr)));
  }
//////////////////////////////////////////////////////// code challenge 27 ////////////////////////////////////////////

  @Test
  public void mergeSortTest() {
    int[] arr = {8, 4, 23, 42, 16, 15};
    assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(App.mergeSort(arr)));
  }

}
