/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array.linked.list;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
          LinkedList list1 = new LinkedList();
    // insert
    list1.insert(1);
    list1.insert(2);
    list1.insert(3);
    list1.insert(50);
    list1.insert(4);
    list1.insert(100);
    list1.insert(300);

    //includes
    System.out.println(list1.include(300));

    // to string
    System.out.println(list1.toString());


    }
}
