/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array.linked.list;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      LinkedList List = new LinkedList();
      // insert method
      List.insert(10);
      List.insert(20);
      List.insert(30);

      //include method
      List.include(2);
      List.include(4);
      List.include(6);

      //toSrting method

      List.toString();



    }
}
