/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTable;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      System.out.println(new App().getGreeting());

      HashTable<String> hash = new HashTable<String>(10);
      hash.add(10, "maram");
      hash.add(5, "rand");
      hash.add(15, "zaina");
      System.out.println(hash.get(5));
      System.out.println(hash.contains(10));

    }
}
