/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    BinarySearchTree tree = new BinarySearchTree();

    tree.add(5 , tree.root);
    tree.add(8 , tree.root);
    tree.add(3 , tree.root);


//    System.out.println(tree.preOrder(tree.root));
//    System.out.println(tree.inOrder(tree.root));
    System.out.println(tree.postOrder(tree.root));

//      System.out.println(tree.contains(5, tree.root));
//      System.out.println(tree.contains(7, tree.root));
//      System.out.println(tree.contains(6, tree.root));


  }
}
